### ISSUE TITLE
Incompatible .mpy file error even with no mpy files copied over

### ISSUE THREAD

**Issue by S4WRXTTCS** [mp-extras/vl53l5cx#1]
Board: STM32F405 Feather Express from Adafruit
CircuitPython 7.0.0

When I run  "from vl53l5cx.cp import VL53L5CXCP" its reporting
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/vl53l5cx/cp.py", line 7, in <module>
MpyError: Incompatible .mpy file. Please update all .mpy files. See http://adafru.it/mpy-update for more info."

Normally this would be straight forwards and I'd simply update the mpy files in the library, but I opted not to copy any of them over as all the .py files were there. I did try copying all the files over per the instructions, but I still got the same error message. 

I did not recreate the vl_fw_config.bin, and instead I used the one in the repository.

**Comment by mgsb** [comment]
It was my mistake to commit the .mpy files. I will push a commit to delete them. Try looking at your CP folder on your STM32 board and delete the .mpy files in lib/vl53l5cx

**Comment by S4WRXTTCS** [comment]
Initially I didn't copy them over to my lib/vl53l5cx so that's why the error message is so confusing. The only binary file is the vl_fw_config.bin file.

I then copied them over to see what it would report, but the error message didn't change. 

I'm now going to try recreating vl_fw_config.bin to see what that does.

**Comment by mgsb** [comment]
Can you show a listing ("dir" or "ls") of the CP drive/folder/directory on the feather board?

**Comment by S4WRXTTCS** [comment]
Sorry, this was a result of my own mistake.

For some reason an older version of the adafruit_bus_device was on my board. So it was triggering off of that, and nothing in this library. 

I need to remember to always erase the entire thing when upgrading CircuitPython versions.

**Comment by mgsb** [comment]
Would be helpful if MP/CP gave the name of the bogus .mpy file in the error message.
